version: "3.5"
services:
  backend:
    build:
      context: boomershub-backend
    ports:
      - 80:5000

  frontend:
    build:
      context: boomershub-frontend
    ports:
      - 80:3000

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
